services:
 hackoladeStudioCLI:
   image: hackolade:latest
   security_opt:
     - seccomp:securityPolicies.json
   volumes:
     - ./appData:/home/hackolade/.config/Hackolade
     - ./data:/home/hackolade/Documents/data/
     - ./logs:/home/hackolade/Documents/HackoladeLogs/
     - ./options:/home/hackolade/.hackolade/options
