services:
  hackoladeStudioCLI:
    image: hackolade:latest
    working_dir: /home/hackolade/Documents
    # security_opt:
    # - seccomp:securityPolicies.json
    # environment:
    # - WITH_SANDBOXING=true
    volumes:
    - hackolade-studio-app-data:/home/hackolade/.config/Hackolade
    - hackolade-studio-logs:/home/hackolade/Documents/HackoladeLogs
    - hackolade-studio-output:/home/hackolade/Documents/output
    # Provide models or inputs from the host (but can be done through named volumes too)
    - ${PWD}/models:/home/hackolade/Documents/models
    # If you have custom options to configure Hackolade like naming conventions or custom properties uncomment the following line
    #  - ./options:/home/hackolade/.hackolade/options

volumes:
  hackolade-studio-app-data: {}
  hackolade-studio-logs: {}
  hackolade-studio-output: {}
